# build on init
tasks:
  - name: Configure ZMP doc environment
    # ensure yarn global and zmp are on the path for this terminal
    before: |
      PATH="$PATH:$(yarn global bin)"
      echo "PATH=\"$PATH\"" >> ~/.bashrc
      echo "BEFORE task complete"
    # install latest version of zmp into workspace
    init: |
      wget --quiet --output-document=$GITPOD_REPO_ROOT/zmprc/zmp https://mrmxf.com/get/zmp ; chmod +x $GITPOD_REPO_ROOT/zmprc/zmp
      echo "INIT task complete"
    # install zmp & clog
    command: |
      sudo wget --quiet --output-document=/usr/local/bin/zmp  https://mrmxf.com/get/zmp  ; sudo chmod +x /usr/local/bin/zmp
      sudo wget --quiet --output-document=/usr/local/bin/clog https://mrmxf.com/get/clog ; sudo chmod +x /usr/local/bin/clog
      echo "COMMAND task complete"

# port for preview server
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint            # lint javascript code
    - piersdeseilligny.betterfountain   # screen writer plugin
    - stkb.rewrap                       # wrap markdown at column boundaries
    - ms-toolsai.jupyter                # jupyter notebook support
    - mads-hartmann.bash-ide-vscode     # bash scripting helper
    - DotJoshJohnson.xml                # xml formatting xpath etc
